# Generated by Django 5.0.6 on 2024-09-22 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_date_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='available_slot',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.availableslot'),
        ),
    ]
