# Generated by Django 5.0.6 on 2024-09-22 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_available_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='available_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.availableslot'),
        ),
    ]
