# Generated by Django 5.0.6 on 2024-09-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_available_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
