# Generated by Django 5.0.6 on 2024-09-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_prescreption_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescreption_model',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
