# Generated by Django 5.0.6 on 2024-09-28 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_prescreption_model_date'),
        ('users', '0002_doctor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescreption_model',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_prescriptions', to='users.doctor'),
        ),
    ]
